services:
  ollama:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-11434}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - letsencrypt-network

networks:
  letsencrypt-network:
    external: true
